# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# ===================================================================

# ----------------------------------------
# SPRING PROPERTIES
# ----------------------------------------

spring:
  # HTTP encoding (HttpEncodingProperties)
  http:
      encoding:
        force: true

  # JACKSON (JacksonProperties)
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: CET

  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    always-use-message-format: true
    basename: messages/messages
    cache-seconds: -1

  # SPRING MVC (WebMvcProperties)
  mvc:
      date-format: dd/MM/yyyy
      locale: en
      throw-exception-if-no-handler-found: true

  # SPRING RESOURCES HANDLING (ResourceProperties)
  resources:
      cache-period: 2592000
      add-mappings: false

  # MONGODB (MongoProperties)
  data:
      mongodb:
        database: concessionaire
        host: ds153003.mlab.com
        password: test
        port: 53003
        username: test

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
      cache: false
      mode: HTML

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  compression:
    enabled: true
  context-path: /concessionaire
  display-name: concessionaire
  error:
    whitelabel:
      enabled: false

# ----------------------------------------
# SECURITY PROPERTIES
# ----------------------------------------
# SECURITY (SecurityProperties)
security:
  enable-csrf: true

# ----------------------------------------
# DATA PROPERTIES
# ----------------------------------------

# EMBEDDED MONGODB (EmbeddedMongoProperties)
#spring.mongodb.embedded.features=SYNC_DELAY # Comma-separated list of features to enable.
#spring.mongodb.embedded.storage.database-dir= # Directory used for data storage.
#spring.mongodb.embedded.storage.oplog-size= # Maximum size of the oplog in megabytes.
#spring.mongodb.embedded.storage.repl-set-name= # Name of the replica set.
#spring.mongodb.embedded.version=2.6.10 # Version of Mongo to use.
