# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# ===================================================================

# ----------------------------------------
# SPRING PROPERTIES
# ----------------------------------------

spring:
  # HTTP encoding (HttpEncodingProperties)
  http:
      encoding:
        force: true

  # JACKSON (JacksonProperties)
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: CET

  # INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    always-use-message-format: true
    basename: messages/messages

  # SPRING MVC (WebMvcProperties)
  mvc:
      date-format: dd/MM/yyyy
      locale: en
      throw-exception-if-no-handler-found: true

  # SPRING RESOURCES HANDLING (ResourceProperties)
  resources:
      cache:
        period: 2592000s
      add-mappings: false

  # MONGODB (MongoProperties)
  data:
      mongodb:
        database: concessionaire
        uri: mongodb+srv://test:test@concessionaire.gusdn.mongodb.net/concessionaire?retryWrites=true&w=majority

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
      cache: false
      mode: HTML

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
  servlet:
     context-path: /concessionaire
     application-display-name: concessionaire
